---
title: "Project Assignments (PA) and Due Dates"
output:
  pdf_document: default
  html_notebook: default
urlcolor: blue
---

The term project is designed to provide you with firsthand experience in designing and carrying out a marketing research project. The project is divided into n assignments, described below. Each completed assignment should be submitted by the date and time specified below. All components of an assignment must be turned in to receive full credit.

# Assignment 1: GROUP FORMATION (8/25 by 5:00 pm)

Your group will work together extensively throughout the semester to complete a term research project. There are four to five members per group. You may choose the members of your group or have the instructor assign you to a group. Group assignments done by the instructor will be on a random basis. During the first two class sessions there will be small group breakout sessions that will allow you to get to know some of your classmates.

By 5:00 pm on this day, submit this assignment on Canvas and indicate:

a\. whether you and three other classmates have formed a team and, if so, the identity of your teammates, or

b\. whether you would like the instructor to assign you to a team.

Submit this assignment on Canvas and indicate:

a)  Title your assignment word document file name with **'Group & team captain's initials'** if you and **three or four** other classmates have formed a team (maximum 5 people in a team). For example, if your team captain is Michael Jordan then you will title your word document as 'Group MJ'. In the word document to be submitted, please include the identity of your teammates including your name in descending order of the first name.

b)  Title your assignment word document file name with **'Random & your initial'** if you would like the instructor to assign you to a team.

This assignment needs to be submitted individually by each student in the class.

<br>

# Assignment 2: TEAM ORIENTATION; PROJECT TOPIC CHOICES (8/ )

On this day, your group should submit the two items below on Canvas.

**(1)** Completed [Team Orientation Assignment](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/Team%20Orientation.docx), including the group project contract.

**(2)** Your group's client sponsor nominations (see underlined material below).

**Nominating Client Sponsors**

Selecting an appropriate client sponsor is critical to the success of your project. The sponsor you select will greatly influence the kind of experience you have with the project over the semester. With an appropriate sponsor, your project can be a rewarding and interesting experience. With the wrong sponsor, you may face difficulties at every stage of the project. Investing time now in selecting an appropriate client will pay big dividends for you.

[Each group is responsible for identifying and conducting initial problem definition with two or three potential clients.]{.ul}

Final client selection will be done in consultation with the instructor.

[Client nominations: The following should be turned in at the beginning of class on the due date]{.ul}:

(1) the names of 2 or 3 clients who are interested in working with your group

(2) for each potential client sponsor include:

-   the business name
-   the name of your contact at the business and his/her email address and telephone numbers
-   a brief description of the problem your project would address (e.g., assess potential demand for opening a new location of the client's frozen yogurt business on the west side of Columbia; determine whether vintage clothing or plus size clothing would be a better use of the upstairs space at the client's retail store, etc.)
-   whether the client has agreed to meet in person with group members for 30-45 minutes within the next few days to discuss the project and its scope; if not, you will need to find another client
-   a brief description of how you would collect data for the project survey and how you would reach those people to survey them

(3) identify which client your group is most interested in working with

**Guidelines for Choosing a Client**

-   Contact several potential clients early - as soon as your group is formed. Contact them in person, definitely not by email and preferably not by telephone. In-person contact increases the chance that your client will be interested in sponsoring your project, and also gives you an opportunity to assess how well the client and his/her business problem fit the project requirements.

-   Your client sponsor should be a local business or campus department (such as the MU Rec Center, the library, or Campus Dining Services) that needs **survey research** to help it solve a marketing problem (however, **do not choose a bar** for your client; also, your client cannot be located in the College of Business). Marketing problems suitable for a project often involve a decision the client is contemplating, for example:

    -   determining whether there is sufficient customer interest to warrant adding an outside dining area to a restaurant

    -   identifying which services and tanning packages would be most effective in attracting more student customers to a tanning salon

    -   determining how to increase potential customers' awareness of a store or other business and identifying which promotions would be most likely to stimulate a visit to the store

<br>

-   Projects that don't involve a specific decision can also be successful if the results of the survey can help the client make important changes to its marketing program, for example:

    -   identifying how the image of a retailer compares with its competitors and what its relative strengths and weaknesses are in the eyes of customers

    -   assessing customer satisfaction with a business's merchandise and services and identifying improvements customers would like to see made to the business

-   Think about how you'll eventually administer the survey. If you're obtaining information about prospective customers, where will you find them? If they're college students, the survey will be relatively easy to conduct. If the prospective customers are families who live on the south side of town, however, you may need to do an intercept survey by standing outside a place where there are lots of local residents, such as the shopping centers near Schnucks or Kohls. Columbia Mall will not let students survey in (or outside) the mall. If your client is a Columbia Mall tenant, however, you can probably survey inside your client's store as long as the client gives permission.

-   Determine whether the proposed project for the client is feasible. Particular consideration is how difficult it will be to contact appropriate people to complete the survey. Most groups will need a sample size of over 150 to 200 qualified respondents, and you should be able to think of a reasonable way to gain the participation of these respondents. In most cases it is not feasible to conduct a telephone survey, and internet surveys are difficult to do because a contact list is needed and most people won't complete them. Most student projects involve intercepting potential respondents in a public place, such as a strip mall or on campus.

-   The project should focus on ***either*** current customers or potential customers, but it's not feasible to include both in one project.

-   The sponsoring client should have a genuine need for the research and not agree to work with you "just to be nice." With a genuine need, the sponsor will be more interested in your project and more responsive when you need feedback at various stages of your work.

-   The sponsor should be enthusiastic about the project and willing to provide the information, assistance, and feedback your group needs in a timely manner. Someone who doesn't return phone calls or emails in a timely manner during the initial contact phase may not be an easy client to work with.

-   The sponsor must be willing to meet in person with your group within a few days so you can complete PA \#3 on time

-   The sponsor should be willing to pay for any necessary and reasonable expenses involved in collecting data for the study, including the cost of duplicating questionnaires and, if necessary, an incentive to reward people for participation (such as a piece of candy or other small token).

-   The instructor has prepared a letter to sponsors that briefly describes the project and the sponsor's responsibilities. You can show this to potential clients to give them an idea of what's involved in the project. You MUST give a copy of the letter to the client sponsor you choose to work with. The letter is available on Canvas (sponsor_letter.pdf).

<br>

**Projects/Clients to Avoid**

-   The client sponsor cannot be the employer of a group member and cannot be an organization that is owned or operated by a relative of a group member.

-   The client must not be doing a project this semester with another Marketing 4050 group.

-   You may not use a bar or nightclub for a client or do a project involving the sale of alcohol. Your client may not be located in the College of Business.

-   Surveys for this project are normally administered in person. In some cases it might be possible to do an internet survey, but these can be very difficult to do and require special instructor permission.

-   Avoid projects where you have to survey officers of a campus organization, because these people are hard to contact and often do not return surveys.

-   Avoid projects where you have to survey business owners, managers, or employees; they are hard to reach.

-   Avoid businesses located near campus or that heavily cater to students, unless the business is new. These businesses are often asked by students to participate in projects and usually want to help, but they are overused for projects and thus are less likely to have a meaningful issue to address in your survey.

-   Avoid a project where the objective is to increase a restaurant's business on slow nights of the week. There really isn't much you can do to help with that problem. If you want to work with a restaurant, choose a more focused topic such as examining the attractiveness of some particular change the owner is contemplating or assessing customer satisfaction.

-   Avoid a project in which the client's objective is "to attract more customers." Such a project will lack focus and be difficult to carry out. The project will be more effective if the client has a specific business change under consideration to attract more customers, in which case your project could focus on the likely effectiveness of the proposed change.

-   The assigned reading on Canvas and the page titled "Some Project Guidelines" in the course packet provides additional useful hints for choosing a topic and dealing with a client. If you're having difficulty finding a client, you can contact the University Center for Innovation and Entrepreneurship in Lafferre Hall (Engineering Bldg.), Room W1026. The center may have some clients who need to have a marketing research study conducted.

-   The sample project reports available on Canvas will give you an idea of the scope of the project and may help you decide whether a client you're considering is appropriate.

<br>

**Hints for topics while talking to clients**

1\. What is the product/service being provided?

2\. What is special 'unique about the product/service?

3\. Does the client know who their competition is?

4\. Is there a special group of people (such as college students) that the product/service is meant for? Are there different groups of people that the client thinks use their product/service?

5\. Does the client think the different groups think of their product/service differently?

6\. What information does the client hope to get from this project? Do they want this information?

7\. What are the different things that the client wants to know? Prioritize these questions.

8\. What decisions will the client make using the information above? There should be several alternatives that you should get from the client for this decision- e.g., where to advertise their product is the decision that will be aided by your project. The decision alternatives would be advertising in Add Sheet, Columbia Tribune, Missourian, Radio, Television etc.

9\. Is the information asked for in item 6 above the best information to make decision in item 8?

10 Create a sample data set (with made up data) and ask the client if this is what they had in mind. This should be done in the second meeting.

<br>

# Assignment 3: DEFINE THE RESEARCH PROBLEM (9/ )

Note this project requires meeting with the professor. See the [signup sheet](https://docs.google.com/spreadsheets/d/13Y4uTVFiYiVHVRIfo_7YZZAFuL6Z6JDR3gUXydcBqK8/edit?usp=sharing).

Note: the PA is highly similar to our [CE1 discussion]().

Your project topic is typical of the kind of problem or decision facing a local business or nonprofit organization. Your group's role is to act as marketing consultants to the business described by your topic.

In this assignment, based on your knowledge of marketing, business principle, and the student population, you will set at least two research objectives for your research project and a set of research questions for each objective that your project will answer. Your assignment should include the following elements:

**(1)** a general statement of the client's problem that the client hopes to solve with the information you will provide in your report.

**(2)** the decision(s) to be made by your client based on your research, and the decision alternatives

**(3)** the target for the decision(s) to be made--is the goal to increase satisfaction/patronage of existing customers or is it to bring new customers to the business. You ***must*** choose ONE of these; for this project, you cannot do both.

**(4)** the client's ***managerial objectives*** for the research project (may overlap with 1 and 2 above)

-   **NOTE regarding managerial and research objectives**: A managerial objective is what the client hopes will result from the research project; examples might be (a) "to develop a more effective advertising campaign" or (b) "to increase the number of college students who shop at our store." A research objective is different from a managerial objective. Your research objective should be to provide information that will help your client reach his/her managerial objective. For the managerial objective in example (a) above, a good research objective might be "to determine which media college students are exposed to most frequently, and which media most strongly influence their purchase behavior." You must provide both a managerial objective (in part 4) and a research objective (in part 5, next) in this assignment.

**(5)** your project's ***research objective(s)***. Your project needs to have at least two research objectives. Some examples are listed below:

-   Assess Columbia residents' awareness and knowledge about a local specialty grocery store that carries international foods.

-   Identity the best media for the store to use to increase awareness.

-   Determine whether customers would like a local restaurant to add a deck for outside dining and how often they would use it.

-   Identify what features customers desire for the deck.

-   Find out how satisfied incoming freshmen are with Mizzou's orientation procedures.

-   Determine what changes would improve incoming freshmen's satisfaction with orientation procedures.

**(6)** a list of research questions for each of the objectives in (5)

Organize this assignment so that each objective is followed by the research questions that are designed to meet each objective

The form of research questions will be discussed in class. You can also look at [example term projects]() to see examples of research questions. Some important points to remember are below.

-   Research questions are [not]{.ul} the same as questionnaire questions. Questionnaire questions are what you ask the consumer on a survey. Research questions are the questions the **manager** wants answered. Put [research questions only]{.ul} in this assignment. Review lecture and [CE 1 discussion](https://github.com/mikenguyen13/mar4050_F21/raw/master/CE1%20%20discussion.docx) to make sure your research questions are phrased appropriately. They should [not]{.ul} include any second person pronouns.

-   The research questions should be very **specific**.

-   You need at least 10 research questions. You can also include a few additional, less important research questions in case there is space for them in the project.

-   **At least one of your research questions must be a group comparison research question** in which you compare groups of people among your respondents. For instance, you might compare heavy or light users of a product; compare students living in three different areas of Columbia with respect to their interest in a particular type of store; compare new versus established customers' brand perceptions, etc. This is called a group comparison research question. **Clearly identify which of your research questions is intended to be a group comparison research question.**

-   Number the research questions so they are easy to refer to.

**REMEMBER**: When you prepare this assignment, **put each research question directly beneath the objective** the research question it relates to.

<br>

This assignment develops the scope of your project, so you must complete your interview with your client before preparing this assignment. Every effort should be made for [***all***]{.ul} group members to meet with the client, not just one or two.

You will meet with the instructor on the due date. Bring [5 copies]{.ul} of this assignment to your meeting. Your double-spaced, typewritten paper (1-2 pages) should include the following:

**(1)** the name of the client business and the contact person you interviewed

**(2)** the names of group members who were present during the interview

**(3)** a general statement of the client's problem that the client hopes to solve with the information you will provide in your report. In addition, provide some brief background information if any is relevant. For instance, you might briefly describe the meeting(s) you've had with your client. You might also explain why the particular topic was chosen.

**(4)** the decision(s) to be made by your client based on your research, and the decision alternatives

**(5)** the target for the decision(s) to be made--is the goal to increase satisfaction/patronage of existing customers or is it to bring new customers to the business. You ***must*** choose ONE of these; for this project, you cannot do both.

**(6)** the client's ***managerial objectives*** for the research project (may overlap with 3 and 4 above)

**NOTE re managerial and research objectives**: A managerial objective is what the client hopes will result from the research project; examples might be (a) "to develop a more effective advertising campaign" or (b) "to increase the number of college students who shop at our store." A research objective is different from a managerial objective. Your research objective should be to provide information that will help your client reach his/her managerial objective. For the managerial objective in example (a) above, a good research objective might be "to determine which media college students are exposed to most frequently, and which media most strongly influence their purchase behavior." You must provide both a managerial objective (in part 6) and a research objective (in part 7, next) in this assignment.

**(7)** your project's ***research objective(s)***. Most projects will have one or two research objectives. Some examples are listed below:

Assess Columbia residents' awareness and knowledge about a local specialty grocery store that carries international foods; identity the best media for the store to use to increase awareness.

Determine whether adding a deck for outside dining would be profitable for a local restaurant and, if so, what features customers desire for the deck.

Find out how satisfied incoming freshmen are with Mizzou's orientation procedures and determine what changes would improve their satisfaction.

**(8)** a list of research questions for each of the objectives in (7).

Organize this assignment so that each objective is followed by the research questions that are designed to meet each objective. The form of research questions will be discussed in class. You can also look at example term projects on Canvas to see examples of research questions. Some important points to remember are below.

**REMEMBER**: When you prepare this assignment**, put each research question directly beneath the objective** the research questions relates to.

-   Research questions are [not]{.ul} the same as questionnaire questions. Questionnaire questions are what you ask the consumer on a survey. Research questions are the questions the **manager** wants answered. Put [research questions only]{.ul} in this assignment. Review lecture and course packet materials to make sure your research questions are phrased appropriately. They should [not]{.ul} include any second person pronouns.

-   The research questions should be very specific.

-   You'll probably need about 10 research questions. You can also include a few, less important research questions in case there is space for them in the project.

-   At least one of your research questions must be a differences research question in which you compare groups of people among your respondents. For instance, you might compare heavy or light users of a product; compare younger, middle-aged, and older consumers with respect to their interest in a particular type of store; compare new versus established customers' brand perceptions, etc. This is called a differences research question. [Clearly identify which of your research questions is intended to be a differences research question]{.ul}.

-   Number the research questions so they are easy to refer to.

**(9)** before turning in the assignment, have your client review your objectives and research questions and make any requested changes.

**(10)** submit a copy of the (Sponsor Agreement Form)[] completed and signed by your client. This form is available on Canvas. Be sure you have provided your client with a copy of the [Sponsor Letter]() (available on Canvas) and with contact information for all group members.

**REMEMBER**: When you prepare this assignment**, put each research question directly beneath the objective** the research questions relates to.

<br>

# Assignment 3.5: DEFINE THE RESEARCH PROBLEM - revise and resubmit.

**Please highlight the changes that you made in green**

# Assignment 4: DESIGN A QUESTIONNAIRE

Note this project requires meeting with the professor and your team members. See the [signup sheet](https://docs.google.com/spreadsheets/d/13Y4uTVFiYiVHVRIfo_7YZZAFuL6Z6JDR3gUXydcBqK8/edit?usp=sharing).

<!-- For your partner team meeting. See [instruction](https://docs.google.com/document/d/1m85mnPgACTD9ecyACWnMdcLEEbtFJmAMJb8Q2LSNMkg/edit?usp=sharing). -->

The questionnaire is one of the most important parts of the project.

Example questionnaires are available

-   [Nike shoes survey](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/example_questionaire/9-running%20shoe%20Qnaire.pdf)
-   [Dishwasher](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/example_questionaire/9-dishwasher%20Qnaire.pdf)
-   [USPS](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/example_questionaire/9-USPS%20survey.pdf)

You can consult these examples for reference regarding ideas about question wording and format and questionnaire layout. Be sure to also look at [Questionnaire Tips](https://drive.google.com/file/d/1dGOVwNOeMThizUgYtZzf3QJZJX5q5tMB/view?usp=sharing).

For this assignment, complete all steps of the questionnaire design process as covered in class. Make sure your questionnaire has been pretested and revised by this date. The questionnaire you turn in should be your final, best work. Submit the following items on Canvas:

-   the message you will use to introduce the survey and ask for participation; put these on a separate page from your questionnaire

-   your questionnaire (downloaded from Qualtrics)

-   your final project objectives and list of research questions; the research questions must be numbered

-   a completed copy of Questionnaire Worksheet A ([WorksheetA template](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/questionaire_worksheet/8-Qnaire%20worksheet%20A.xls))

-   a completed copy of Questionnaire Worksheet B ([WorksheetB template](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/questionaire_worksheet/8-Qnaire%20worksheet%20B.xls))

The questionnaire must include [screener questions]{.ul} (if relevant) and [a complete set of demographic questions]{.ul} appropriate to the people you are surveying.

<br>

For this assignment, complete the questionnaire design process through Step \#8. Make sure your questionnaire has been pretested and revised by this date. The questionnaire you turn in should be your final, best work. On this date, bring to class the items listed below. The required number of each of these items must be available at the beginning of class.

-   the oral instructions you will use to introduce the survey, including any qualifier or screener questions; put these on a separate page from your questionnaire
-   five (5) blank copies of your questionnaire
-   five (5) copies of your final project objectives and list of research questions; the research questions must be numbered
-   one completed copy of Questionnaire Worksheet A (a template is available on Canvas)
-   one completed copy of Questionnaire Worksheet B (template also available on Canvas)

Unless an exception is granted by the instructor, the questionnaire should fit on the front and back of a single sheet of letter size paper. It must include a complete set of demographic questions appropriate to the people you are surveying.

Also, plan a meeting with your client in which you show the client your final problem definition and a copy of your questionnaire. At this meeting, have the client sign the [Project Review Statement](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/project%20review%20statement.docx). You will turn in this signed statement when you turn in PA \#6.

# Assignment 5: CLIENT CHECK, REVISED COPY OF QUESTIONNAIRE, SAMPLING PLAN, AND MEETING WITH INSTRUCTOR ()

On this date, turn in the following items on Canvas:

-   the message you will use to introduce the survey and ask for participation; put these on a separate page from your questionnaire

-   the final version of your questionnaire, which has been revised based on classmates' reviews of your questionnaire

-   your final project objectives and list of research questions; the research questions must be numbered

-   a revised copy of Questionnaire Worksheet A, incorporating changes made to the questionnaire based on the classroom review

-   a revised copy of Questionnaire Worksheet B, incorporating changes made

-   your sampling plan

Also on this date your group will have a meeting with your instructor to review your questionnaire and your group's sampling plan. Bring printed copies of the following materials to this meeting:

(1) [Project Review Statement](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/project%20review%20statement.docx) signed by group members and the client

(2) Sampling Plan (3 printed copies)

(3) Questionnaire (3 printed copies)

The sampling plan is a complete description of how you will choose individuals to participate in your survey. Sampling plans have been described in class and an example sampling plan are included in this packet. Before completing the sampling plan, review the Sampling Plan Checklist in the course packet (p. 11-10) The plan may be presented in outline form. Your sampling plan must include a completed time sampling grid (typed).

Revise and resubmit Assignment 4 - Design a questionnaire

Please **highlight** the changes that you made in green on both the questionnaire and the worksheet A and B.

<br>

# Assignment 6: CODEBOOK PREPARED ()

Prepare a codebook for entering your survey data into Excel. Submit your codebook on Canvas.

Codebooks for Research Projects

The codebook contains information about the variables in your study. At the top of the codebook is a title and a sentence or two describing the study. This is followed by information concerning each of the variables in your survey. For each variable, the following should be included.

-   The variable name (must not begin with a number)
-   Source of the variable (usually the question number on the survey)
-   Acceptable values for the variable and their definitions

[An example codebook for the library questionnaires](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/questionaire_worksheet/Coodbook%20for%20the%20library%20questionnaire.xlsx).

<br>

# Assignment 7: DATA COLLECTION UNDERWAY ()

Also by this date, you should have obtained completed questionnaires from at least 50 respondents (roughly 10 questionnaire per person). Respondents must be chosen according to your sampling plan. Photograph the front page of each completed questionnaire and submit the photos on Canvas. The remaining data collection needs to be completed by the Assignment \#7 due date.

<br>

# Assignment 8: DATA COLLECTION COMPLETED, EXCEL DATA FILE PREPARED ()

Your data collection must be completed by this date and your data entered into an Excel spreadsheet. Turn in your Excel spreadsheet on Canvas.

[Make sure that at least everyone in your group have access to the complete data file]{.ul}.

<br>

# Assignment 9: PREPARE FOR DATA ANALYSIS

This assignment requires no new work by team members. However, when class begins, each team member should have in his/her possession the following items to refer to during class:

-   your final list of research questions (numbered)

-   the final version of your team's questionnaire

-   Questionnaire Worksheet B (updated final version)

You are allowed to bring your laptop to the class to access these materials.

<br>

# Assignment 5: COMPLETE DATA COLLECTION, DATA COLLECTION RESULTS REPORT

Complete your data collection. Each team will need 160\~200 completed questionnaires to have enough sample size to do the subsequent data analysis.

Prepare a results report in Qualtrics. Go to Projects in Qualtrics and do the following to get your report.

1.  Select your project and then click on Reports (in the gray bar near the top).

2.  Click the button for Share Report (toward the upper right) and select Word Document.

3.  Be sure that Select All is checked in the dialog box that appears; click Export Pages.

4.  In the box that appears, click Download (may take a few seconds to appear)

If you have trouble finding the downloaded report on your computer, search for "Default Report.docx"

Submit your results report on Canvas.

<br>

# Assignment 10: DATA ANALYSIS PLAN ()

Type the data analysis plan for your project that you develop in class into a formal document, using the [Data Analysis Plan template](https://drive.google.com/file/d/1hFg5ipjgmUWCkkyC8wLIaBnNijf8N3if/view?usp=sharing) and the [cheat sheet](https://docs.google.com/spreadsheets/d/14IsWrKChT5sRHDjbgIzI41cA7Q6AzSCYRLGiKQ5yv_k/edit?usp=sharing). [Include at least one group comparison analysis in your data analysis plan]{.ul}. You can use this [Qualtrics guide](https://drive.google.com/file/d/1uwyQz2LCU0MSYEZJ1oxITdBiomQla9s2/view?usp=sharing) for the group comparison research questions. You don't need to do the analysis yet, you only need to plan for the analysis.

Submit your typed data analysis plan on Canvas including:

(1) your typed data analysis plan

(2) your research questions and research objectives

(3) your questionnaire & Questionnaire Worksheet B (updated final version)

(4) the Results Report from Qualtrics (see PA 5)

when the actual in-class analysis begins, each team member should have in his/her possession the above items to refer to during class.

<br>

# Assignment 11: MID-SEMESTER PEER EVALUATION

In this assignment, you will evaluate your own performance throughout the project and that of other members of your group on the major project assignments completed so far. [A Word version of the evaluation form](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/Mid-semester%20peer%20evaluation%20form.docx) is available on Canvas. Download the form, complete it, then submit on Canvas. (remember to put it on Canvas, not as a word doc for student)

This evaluation is confidential and will not be shared with group members. However, if you have a concern about your level of contribution to the project, or the contribution of another group member, you are encouraged to discuss this with your group. Regardless, it is a good time of the semester to take a few minutes of a regularly scheduled group meeting to discuss the following issues:

-   is communication in the group working effectively? Are there ways it could be improved?

-   is everyone doing their fair share of work? Is anyone feeling over-burdened?

-   what significant contributions has each group member made to the project so far?

-   what changes could each group member make to enhance group functioning?

# Assignment 12: INITIAL DATA ANALYSIS REPORT

To answer your research questions, you must analyze your data. In the assignment, you will conduct the analyses to answer your research questions and summarize the results in a pdf document. [Be sure to number the pages on this document]{.ul}. You can consult the following documents that we went through in class:

1.  You can use this [Qualtrics guide](https://drive.google.com/file/d/1uwyQz2LCU0MSYEZJ1oxITdBiomQla9s2/view?usp=sharing) for the difference research questions.

2.  You can use the lecture slides [Descriptive Statistics (means, frequencies, crosstabs)](https://drive.google.com/file/d/128nJxj9V3o4HOVajncStfItfAEcNjPPo/view?usp=sharing) for the difference questions bar-charts.

3.  You can use the [analysis techniques](https://mailmissouri-my.sharepoint.com/:x:/g/personal/ylb3c_umsystem_edu/EeYgQWvbg3NHsFYaKMe4hqMBRXjaRjkU3IJ7W57lZMwyFA?e=ySDwtD) excel sheet when you do actual analysis.

4.  You can consult the [level of measurement common issues](https://docs.google.com/document/d/1tz06AxAxUWbbhGNhJnae5nunS54TUeoLHgxAQUR4yF8/edit?usp=sharing) for your revision on the level of measurement.

5.  You **should** consult the [Sample student projects](https://drive.google.com/file/d/11SbGxUXGmUYsVaeKNiF-9rb3eXC0oD_h/view?usp=sharing) for its **result session** (from pages 29 to 49) on the **expected PA outputs**. The analysis report is organized by research question and should include the following:

For each research question

-   write out the research question

-   indicate which questionnaire question answers the research question

-   indicate the statistical test used to answer the question (percent, crosstabulation, etc.)

-   briefly describe the answer to the research question.

-   for each research question, copy and paste the relevant part of the Qualtrics Results Report into your document.

-   add bar chart to visualize the results.

You can use an outline format for your report. [Submit the report on Canvas]{.ul}.

<br>

# Assignment 13: MEETING WITH INSTRUCTOR (optional) (Meeting ; sign by up )

On this date, you may meet with your professor to ask questions about your presentation or anything else. If you have questions about your data analysis results, bring the following with you to your meeting:

-   your questionnaire

-   your data analysis plan (Assignment \#10, updated)

-   initial data analysis report (PA \#12)

<br>

# Assignment: Extra credit - STATISTICAL TESTS 10 points

Completing this assignment will gain your ten extra points in total or five points per analysis.

You need to apply **up to two analyses** among following statistical tools that we covered for second exam: a) confidence interval for mean b) confidence interval for percent c) independent t test d) two way chi-square test

Follow the same format as the Assignment 12: INITIAL DATA ANALYSIS REPORT on those appropriate research questions.

<br>

# Assignment 14: TERM PROJECT PRESENTATION ()

Notify your client in advance of the presentation date and time and invite your client to attend. Provide a map and parking information if necessary. The instructor can provide a parking permit (which requires name, license plate, make, model, and color to submit to Halsey) for your client if you provide **four days** advance notice.

On the day of your presentation [before 9:00 am, submit your presentation PowerPoint deck (or your choice of presentation tools) on Canvas]{.ul},

-   The presentation of your term project should cover the topics described on the [Pointers on Presentations](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/presentation/Pointers%20on%20presentations.docx).

-   The presentation can be either PowerPoint format, Google Slides or Prezi.

-   During the presentation, the monitor at the back of the room will be turned off so that you can get more practice in a setting similar to what you will encounter in a business environment.

-   While preparing the presentation, carefully read and follow the Pointers on Presentations and review [the slides design tips](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/presentation/Presentation%20slide%20examples.pptx) and the [sample student presentation slides](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/presentation/Sample%20Student%20Presentation%20from%20previous%20semester.pptx) for reference.

-   The presentation should last between 12 and 14 minutes. If you go under or over this time frame, there is a grade deduction of 1 point per minute. The class will have an opportunity to ask you questions following your presentation.

-   Your presentation will be graded on the criteria described in "[Presentation Evaluation Form](https://github.com/mikenguyen13/mar4050_F21/blob/master/project_assignment/presentation/Presentation%20Evaluation%20Assignment.docx)."

-   Each person will submit an evaluation for every group.

-   You are responsible for practicing your presentation on the classroom equipment before presentation day and making sure that everyone in the group is familiar with how the equipment works.

-   On presentation day, you must be set up and ready to go [before]{.ul} the beginning of class. If you are not ready at that time, there will be point deductions and you may be asked to give your presentation at another time. Class time is very tightly scheduled during presentation days, and it is necessary that all groups be ready to present at the appointed time.

<br>

# Assignment 15: PRESENTATION CRITIQUE ()

This assignment is due 11/20 if your presentation was on 11/18.

It's due 12/2 if your presentation was on 11/30.

Prepare a written critique of the presentations of your **paired four other peer teams**, based on their video recording. Details of the critique assignment are described in the "[Presentation Evaluation Form](https://docs.google.com/document/d/15P8bHYcZ5shXgm6F2nqEfhUCn_GbDkQsEE-M41pcWm8/edit)". The video recording for each presentation team is included as a link in the evaluation sheet under each presentation team number.

Upload a screenshot of your task completion to the Canvas assignment.

<br>

# Assignment 16: WRITTEN PROJECT REPORT ()

Sample student projects ([1](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/written_report/example1%20SlideDoc%20research%20report.pdf), [2](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/written_report/example2%20SlideDoc%20research%20report.pdf)) are available. [Report format](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/written_report/Slidedocs%20report%20templates.pptx) and other guidelines are covered in class. See also the material titled "[Project Report Guidelines](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/written_report/Project%20Report%20Guideline.pdf)".

For this assignment, submit an electronic copy of your report on Canvas.

This assignment contains 3 parts:

(1) Submit an electronic copy of your report on Canvas

(2) Provide your client each of the following items by this date:

-   a printed and bound copy of your report

-   a hard copy and an electronic copy of the client Project Evaluation Form (available on Canvas)

-   contact information for all group members

-   in addition, the group must make itself available to your client to discuss the report should he/she have questions.

(3) Turn in the Statement of Submission to Client form (course packet p. 30-2). This statement acknowledges that you have provided the above items to your client. Turn in a copy of this statement, [signed by the contact person for your client company]{.ul} and by all group members, to the instructor. [If this form isn't received in time, all group members will receive an incomplete for the class]{.ul}. The incomplete will be removed with the instructor receives the signed form.

NOTE:

-   You may wonder what the difference between the presentation (if you use powerpoint) and the written report. In the presentation, you have 10-12 minutes to present in the most succinct way about your research project, which means that you might not be able to address all the research questions. However, in the report, you can put everything that is of interest to the consumers of that report (e.g., managers).
-   If you attempt to submit the same powerpoint presentation as your written report. You will receive no points for this assignment because you did not perform any work for this assignment.

<br>

# Assignment 17: PEER EVALUATION ( by 5 pm)

In this assignment, you will evaluate your own performance throughout the project and that of other members of your group. [Download the form](https://github.com/mikenguyen13/mar4050_F21/raw/master/project_assignment/peer%20evaluation.docx), complete it, then submit on Canvas before 5 p.m. on this date. on this date. If this form is not submitted, you may receive an incomplete grade for the course.
